// <auto-generated />
namespace SaleManagement.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addWxbinding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWxbinding));
        
        string IMigrationMetadata.Id
        {
            get { return "201609250447382_addWxbinding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
