// <auto-generated />
namespace SaleManagement.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddShippingScheduleSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShippingScheduleSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "201609141555101_AddShippingScheduleSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
