// <auto-generated />
namespace SaleManagement.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hotselling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hotselling));
        
        string IMigrationMetadata.Id
        {
            get { return "201903100535560_hotselling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
