// <auto-generated />
namespace SaleManagement.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class spotgoodpattentype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(spotgoodpattentype));
        
        string IMigrationMetadata.Id
        {
            get { return "202203230620286_spotgoodpattentype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
